### ISSUE TITLE
An action actually ends in errors, but it shows that action is succeeded

### ISSUE THREAD

**Issue by yutopp** [peaceiris/actions-hugo#362] opened 2020-06-20 21:22 UTC
## Describe the bug

Although an action seems to be failed by an exception, it passed a CI steps in exit code 0. Maybe exceptions in the async functions are not handled in correctly.

## To Reproduce

Set a wrong version of Hugo to `hugo-version` parameter. Please see YAML file section.

## Expected behavior

Stop CI steps with error messages.

## Screenshots

![image](https://user-images.githubusercontent.com/219797/85211470-7ea4b580-b384-11ea-8f2e-bc07f5cf624e.png)

The step was succeeded with a green check, but actually it failed and stacktraces are printed.

## Your YAML file

(I used this action in the private repo, thus I prepared a snippet)

```
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'v0.72.0'
```

In this case, `hugo-version` is wrong (it should be '0.72.0'). Then the action will be failed with downloading a Hugo by HTTP 404.

**Comment by peaceiris** [comment] 2020-06-21 03:57
Thanks.

Duplicate of #310

**Closed** 2020-06-21 04:16 UTC
Labels: bug

**Comment by peaceiris** [comment] 2020-06-21 04:26
[Release actions-hugo v2.4.12 · peaceiris/actions-hugo](https://github.com/peaceiris/actions-hugo/releases/tag/v2.4.12) has been released. Thank you for your contribution!
ʕ◔ϖ◔ʔ
